FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the project
COPY . .

# Expose the default Angular port
EXPOSE 4200

# Run the Angular dev server
CMD ["npm", "start"]
